version = 0.1

default-task = "copy:build"

[[task]]
name = "build:umd"
target = "dist/index.umd.js"
deps = ["src/##.ts"]
run = "vite build"

[[task]]
name = "build:esm"
target = "dist/index.mjs"
deps = ["src/##.ts"]
run = "vite build"

[[task]]
name = 'build:iife'
target = "dist/component.mjs"
deps = ['src/##.ts']
run = "vite build -c vite.config.iife.js"

[[task]]
name = 'copy:build'
target = 'test/index.umd.js'
deps = ['build:umd', 'build:esm', 'build:iife']
run = "cp dist/index.umd.js test"

[[task]]
name = 'test'
target = 'test/index.html'
deps = ['copy:build']
run = 'npx http-server test'
